name: Deploy Core Infra

on:
  workflow_dispatch:  # Manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: Terraform-Infra-Core/tf
        run: terraform init

      - name: Terraform Plan
        working-directory: Terraform-Infra-Core/tf
        run: terraform plan -var-file=../tf-project/dev-tfvars.json

      - name: Terraform Apply
        working-directory: Terraform-Infra-Core/tf
        run: terraform apply -auto-approve -var-file=../tf-project/dev-tfvars.json

      - name: Upload Terraform State
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: Terraform-Infra-Core/tf/terraform.tfstate

