name: Deploy Core Infra

on:
  workflow_dispatch:  # 👈 This enables manual trigger in GitHub UI

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: tf
        run: terraform init

      - name: Terraform Plan
        working-directory: tf
        run: terraform plan -var-file=../tf-project/dev.tfvars.json

      - name: Terraform Apply
        working-directory: tf
        run: terraform apply -auto-approve -var-file=../tf-project/dev.tfvars.json
