name: Patch Remote Servers

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  patch-servers:
    runs-on: self-hosted  # Uses the self-hosted runner inside VirtualBox
    steps:
      - name: Connect & Patch Multiple Servers
        env:
          SSH_HOSTS: ${{ secrets.SSH_HOSTS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key  # Create SSH key file
          for host in $SSH_HOSTS; do
            echo "Connecting to $host..."
            ssh -i private_key -o StrictHostKeyChecking=no "$SSH_USER@$host" <<EOF
echo "Connected to $(hostname)"
sudo apt update && sudo apt upgrade -y
sudo shutdown -r now  # Reboot the server
EOF

          echo "Reboot triggered on $host."
          done

          rm -f private_key  # Remove SSH key after execution

