name: Patch Remote Servers

on:
  workflow_dispatch:  # Manually triggered
  schedule:
    - cron: '0 3 * * 1'  # Runs every Monday at 3 AM UTC
jobs:
  patch-servers:
    runs-on: self-hosted  # Uses the self-hosted runner inside VirtualBox
    steps:
      - name: Connect & Patch Multiple Servers
        env:
          SSH_HOSTS: ${{ secrets.SSH_HOSTS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key

          for SERVER in $SSH_HOSTS; do
            echo "Patching $SERVER..."
            ssh -o StrictHostKeyChecking=no -i private_key $SSH_USER@$SERVER << 'EOF'
              echo "Connected to $(hostname)"
              sudo apt update && sudo apt upgrade -y
              sudo apt autoremove -y
              echo "Patching completed on $(hostname)"
      EOF
          done

           rm -f private_key
