name: Patch Remote Servers

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  patch-servers:
    runs-on: self-hosted  # Uses the self-hosted runner inside VirtualBox
    steps:
      - name: Connect & Patch Multiple Servers
        env:
          SSH_HOSTS: ${{ secrets.SSH_HOSTS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key  # Create SSH key file

